server:
  port: 8067
  servlet:
    context-path: /api

spring:
  flyway:
    # postgresql支持
    locations: classpath:migration/postgresql
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://175.178.54.6:5432/vben
    username: root
    password: 1q2w3e4R
  messages:
    basename: i18n/international
    fallback-to-system-locale: true
    encoding: UTF-8
    cache-duration: 3600

mybatis-plus:
  global-config:
    banner: off
mybatis-plus-join:
  banner: false
sa-token:
  is-print: off
  # token 名称（同时也是 cookie 名称）
  token-name: Authorization
  # token前缀
  tokenPrefix: Bearer
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: tik
  # 是否输出操作日志
  is-log: false